site_name: KITON
site_description: Полная документация по Telegram-боту для организации взаимодействия между учениками, репетиторами и родителями
site_author: KITON 
site_url: https://skand21.github.io/KITON-DOCS

# Репозиторий скрыт

# Навигация
nav:
  - Главная: index.md
  - 👨🏫 Для репетиторов:
    - Обзор: tutor/index.md
    - Начало работы: tutor/start.md
    - Управление учениками: tutor/students.md
    - Домашние задания: tutor/homework.md
    - Расписание: tutor/schedule.md
    - Статистика: tutor/statistics.md
    - Система "Газики": tutor/gamification.md
    - Тарифы: tutor/tariffs.md
    - Партнерство: tutor/partnership.md
    - FAQ: tutor/faq.md
  - 👨🎓 Для учеников:
    - Обзор: student/index.md
    - Быстрый старт: student/start.md
    - Домашние задания: student/homework.md
    - Расписание: student/schedule.md
    - Система "Газики": student/gamification.md
    - Твой прогресс: student/progress.md
    - Баланс и оплаты: student/balance.md
    - Общение с репетитором: student/communication.md
  - 👨‍👩‍👧 Для родителей:
    - Обзор: parent/index.md
    - Подключение к ребенку: parent/connect.md
    - Контроль обучения: parent/monitoring.md
    - Финансы: parent/finances.md
    - Общение с репетитором: parent/communication.md
    - Аналитика: parent/analytics.md
    - Система "Газики": parent/gamification.md
    - Уведомления: parent/notifications.md
  - 💰 Продажные материалы:
    - Кейсы успеха: sales/success-cases.md
    - Сравнение с конкурентами: sales/competitors.md
    - ROI калькулятор: sales/roi-calculator.md
  - 🆘 Поддержка:
    - Техническая поддержка: support/technical.md
    - Обновления: support/updates.md
    - Контакты: support/contacts.md
    - Вебинары: support/webinars.md
    - Демонстрации: support/demos.md
    - Обзор обновлений: support/update-overview.md
    - Обучение функциям: support/feature-training.md
    - Примеры наград: support/rewards-examples.md
    - Шаблоны: support/templates.md
  - 📋 Обновления: updates.md
  - 🆘 Поддержка: support.md
  - ❓ FAQ: faq.md

# Тема
theme:
  name: material
  language: ru
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Переключить на светлую тему
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Переключить на темную тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view

# Плагины
plugins:
  - search:
      lang: ru

# Дополнительные настройки
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

# Исключаем README.md из сборки
exclude_docs: |
  README.md

# Дополнительные файлы
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/kiton_support
    - icon: fontawesome/brands/github
      link: https://github.com/skand21/KITON-DOCS
  last_updated: "2025-01-10"
  css: []
  js:
    - javascripts/auto-theme.js
    - javascripts/progress.js
    - javascripts/search-enhancement.js
    - javascripts/color-picker.js
    - javascripts/hide-anchors.js
    - javascripts/mobile-menu-fix.js
