site_name: KITON
site_description: Полная документация по Telegram-боту для организации взаимодействия между учениками, репетиторами и родителями
site_author: KITON 
site_url: https://skand21.github.io/KITON-DOCS

# Репозиторий скрыт

# Навигация
nav:
  - Общая информация: index.md
  - FAQ: faq.md
  - Гайды:
    - Репетиторы: tutor-guide.md
    - Ученики: student-guide.md
    - Родители: parent-guide.md
  - База знаний:
    - Общая информация: knowledge-base.md
    - Для репетиторов: knowledge-base-tutor.md
    - Для учеников: knowledge-base-student.md
    - Для родителей: knowledge-base-parent.md
  - Тарифы: tariffs.md

# Тема
theme:
  name: material
  language: ru
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Переключить на светлую тему
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Переключить на темную тему
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit
    - content.action.view

# Плагины
plugins:
  - search:
      lang: ru

# Дополнительные настройки
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
  - admonition
  - footnotes
  - toc:
      permalink: true

# Исключаем README.md из сборки
exclude_docs: |
  README.md

# Дополнительные файлы
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/kiton_support
    - icon: fontawesome/brands/github
      link: https://github.com/skand21/KITON-DOCS
  last_updated: "2025-01-10"
  css: []
  js:
    - javascripts/auto-theme.js
    - javascripts/progress.js
    - javascripts/search-enhancement.js
    - javascripts/color-picker.js
    - javascripts/hide-anchors.js
    - javascripts/mobile-menu-fix.js
